checks:
  php: true

filter:
  paths:
    - "src/*"

tools:
  external_code_coverage:
    timeout: 600    # Timeout in seconds.
    runs: 1         # How many code coverage submissions Scrutinizer will wait
